# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e891d7c2aa28b9e1e3372d1f23da4674947467246236cd54583f22d1cdf6ec7af1b330b0ceea104bc32eb930f2f0a71d8b801d70ef7fe86e3e6b5ed21ef9f91
  admin_name: name
  admin_password: password

test:
  secret_key_base: fe84e98518ee0baeded3eeaf2097131b43632cb61eca0df6a096f118ce54f16f96d610d968021ec838d5eafd272cf94075d7e6f38c0c701fb9edfda0e5368246
  admin_name: name
  admin_password: password

production:
  secret_key_base: ENV['SECRET_KEY_BASE']
  admin_name: ENV['DD_NAME']
  admin_password: ENV['DD_PASSWORD']
