# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#
Case.create(title: "Ahmed v Metroline Travel Ltd UKEAT/0400/10/JOJ",
            summary: "At a pre-hearing review the ET held that C was not disabled for the purposes of s.1 DDA 1995.  C appealed.  At a pre-hearing review the ET held that C was not disabled for the purposes of s.1 DDA 1995.  C appealed.",
            facts: "In 2008, C , who was a bus driver, suffered a whiplash injury in an accident.  He did not return to work. Initially R’s doctor agreed that C was unfit for work and indicated that C would benefit from physiotherapy to help speed up recovery.  However, in February 2009 R’s doctor (Dr Kahtan) advised that C was fit for work.  She also stated that C had said a number of things which were inconsistent with him having a disability; for example that he was driving his own car, playing football with his children and lifting weights.  After two medical capability hearings C was dismissed for incapability.  C denied that he had been properly examined in February 2009 and denied saying the things that Dr Kahtan alleged he had.  C brought a claim of disability discrimination.  The ET accepted Dr Khatan’s account of the February 2009 meeting and held that C was not disabled.",
            held: "Since the dispute of fact between Dr Khatan and C did not concern all the activities that C said he could not perform and since the ET did not refer to all of C’s activities, C argued that the ET wrongly focused on those activities he could do rather than on those that he could not.  The EAT disagreed and stated that the ET’s acceptance of Dr Khatan’s evidence was an implicit rejection of C’s credibility.

Although the ET, when making its decision, referred to the statutory Guidance, it did not refer to any particular part of it.  C argued that the ET failed to have regard to the statutory Guidance in accordance with the decision in Goodwin v The Patent Office [1999] ICR 302.  The EAT rejected this argument and stated that it was satisfied, from reading the judgment, that the employment Judge understood the potential relevance of the Guidance and the importance of using it correctly. ",
            comment: "The facts of this case are perhaps more interesting and informative than the discussion of the legal principles.  The Respondent successfully argued that C’s account of his disability was false and that he was not disabled even though C had produced medical evidence from a consultant and his GP and even though R had dismissed C for incapability.  It shows the value of seeking independent medical advice at an early stage and taking a robust approach to the question of whether or not the Claimant has a disability.")
